# Generated by Django 5.0.6 on 2024-07-09 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colf', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='indumentaria',
            old_name='talle',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='indumentaria',
            old_name='sexo',
            new_name='tipo',
        ),
        migrations.RenameField(
            model_name='maqmusculacion',
            old_name='calidad',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='maqmusculacion',
            old_name='gamma',
            new_name='tipo',
        ),
        migrations.AlterField(
            model_name='accesorios',
            name='precio',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='indumentaria',
            name='precio',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='maqcardio',
            name='precio',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='maqmusculacion',
            name='precio',
            field=models.CharField(max_length=1000),
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='avatares')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
