# Generated by Django 5.0.6 on 2024-07-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colf', '0002_rename_talle_indumentaria_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indumentaria',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='maqmusculacion',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
    ]
