# Generated by Django 5.0.6 on 2024-07-20 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colf', '0004_alter_avatar_imagen_alter_avatar_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='indumentaria',
            name='imagen',
            field=models.ImageField(default='indumentaria/default.jpg', upload_to='indumentaria/'),
        ),
        migrations.AlterField(
            model_name='indumentaria',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
