# Generated by Django 5.0.6 on 2024-07-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colf', '0005_indumentaria_imagen_alter_indumentaria_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesorios',
            name='imagen',
            field=models.ImageField(default='accesorios/default.jpg', upload_to='accesorios/'),
        ),
    ]
