# Generated by Django 5.0.6 on 2024-07-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colf', '0006_accesorios_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='maqmusculacion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='maqmusculacion/'),
        ),
        migrations.AlterField(
            model_name='accesorios',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='accesorios/'),
        ),
        migrations.AlterField(
            model_name='maqmusculacion',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
