# Generated by Django 5.0.6 on 2024-07-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colf', '0007_maqmusculacion_imagen_alter_accesorios_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maqcardio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='maqcardio/'),
        ),
    ]
